name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install requirements
        run: pip install -r requirements.txt

      - name: build
        run: pyinstaller --noconfirm --clean --onefile --name supabase-secrets-generator main.py

      - name: move file
        run: mkdir -p dist/${{ matrix.os }} && mv dist/supabase-secrets-generator dist/${{ matrix.os }}/supabase-secrets-generator

      - name: publish
        uses: actions/upload-artifact@v3
        with:
          name: supabase-secrets-generator
          path: dist

  release:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: download macos build
        id: macos
        uses: actions/download-artifact@v3
        with:
          name: dist/macos-latest
          path: dist

      - name: download ubuntu build
        id: ubuntu
        uses: actions/download-artifact@v3
        with:
          name: dist/ubuntu-latest
          path: dist

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.macos.outputs.download-path }}
            ${{ steps.ubuntu.outputs.download-path }}
          tag_name: latest
          name: ${{ github.event.repository.updated_at }}
          fail_on_unmatched_files: true
